### ISSUE TITLE
[JOSS] Examples

### ISSUE THREAD

**Issue by RMeli** [Degiacomi-Lab/molearn#8]
Running `analysis_example.py` in the `examples/` folder results in the following error:

```python
FileNotFoundError: [Errno 2] No such file or directory: 'xbb_foldingnet_checkpoints\\checkpoint_no_optimizer_state_dict_epoch167_loss0.003259085263643.ckpt'
```

This happens similarly for the following paths:
https://github.com/Degiacomi-Lab/molearn/blob/070520c52945427efef070b28c55805330c98f92/examples/analysis_example.py#L32-L33

I'd suggest to use `os.path.join` to concatenate paths.

---

https://github.com/openjournals/joss-reviews/issues/5523

**Comment by RMeli** [comment]
This is a bonus and not required at all for JOSS, but would it be possible to add a plotting output of the analysis script?

https://github.com/Degiacomi-Lab/molearn/blob/070520c52945427efef070b28c55805330c98f92/examples/analysis_example.py#L50-L58

The "generating error landscape" phase takes some time so the suspense runs high and it's a bit deceiving not to get any output. =)

**Comment by RMeli** [comment]
When running `bb_example_subclassing_trainer.py` I get the following error:

```
Traceback (most recent call last):
  File "/home/rmeli/git/molearn/examples/bb_example_subclassing_trainer.py", line 127, in <module>
    trainer.run(max_epochs = 32+trainer.epoch,**runkwargs)
  File "/home/rmeli/git/molearn/src/molearn/trainers/trainer.py", line 181, in run
    logs.update(self.valid_epoch(epoch))
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmeli/git/molearn/examples/bb_example_subclassing_trainer.py", line 87, in valid_epoch
    results['valid_DOPE'] = dope[:,0].mean()
                            ~~~~^^^^^
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

Printing the shape of `dope` I get `(8,)`.
